coverage:
  status:
    project:
      target: 90%
    patch:
      target: 90%
comment:
  layout: "diff"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes
